#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate the iOS app's English + Chinese .strings tables from the Swift
source and tools/i18n/translations.json.

Workflow (see README.md):
  1. Add / change Chinese UI strings in the SwiftUI code. Either:
       - write them bilingual  Text("设置 / Settings")   → auto-split, OR
       - write them Chinese-only Text(L("设置")) and add the English to
         tools/i18n/translations.json.
     Interpolated / String-typed values go through L(...) / Lf("中文 %@", arg).
  2. Run:  python tools/i18n/gen_strings.py
  3. Commit the regenerated en.lproj / zh-Hans.lproj + translations.json.

Self-contained, stdlib only, repo-relative paths (run from anywhere).
Skips // comments and unescapes source escapes (\\n etc.) so the generated
keys match what L() receives at runtime.
"""
from __future__ import annotations

import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APP = os.path.join(ROOT, "client", "AAALionApp", "AAALionApp")
TRANS_PATH = os.path.join(ROOT, "tools", "i18n", "translations.json")

_HAN = re.compile("[一-鿿]")
_LATIN = re.compile("[A-Za-z]")
_LITERAL = re.compile(r'"((?:[^"\\]|\\.)*)"')
# strings we must NOT translate (regex patterns / asset paths / format fragments)
_NON_UI = re.compile(r"static/|com\.aaalion|加入\?购物|下单\|结|String\(format")


def _unescape(s: str) -> str:
    """Swift source escapes -> runtime chars, so the .strings key matches what
    L() receives at runtime (Swift turns \\n into a real newline)."""
    out, i = [], 0
    table = {"n": "\n", "t": "\t", '"': '"', "\\": "\\", "'": "'", "0": "\0"}
    while i < len(s):
        if s[i] == "\\" and i + 1 < len(s):
            out.append(table.get(s[i + 1], "\\" + s[i + 1]))
            i += 2
        else:
            out.append(s[i])
            i += 1
    return "".join(out)


def _extract_keys() -> list[str]:
    keys: dict[str, bool] = {}
    for f in glob.glob(os.path.join(APP, "**", "*.swift"), recursive=True):
        if os.path.basename(f) == "LanguageManager.swift":
            continue
        with open(f, encoding="utf-8") as fh:
            for line in fh:
                code = line.split("//", 1)[0]  # ignore // comments
                for m in _LITERAL.finditer(code):
                    raw = m.group(1)
                    if _HAN.search(raw):
                        keys[_unescape(raw)] = True
    return list(keys)


def _is_bilingual(k: str) -> bool:
    return " / " in k and bool(_LATIN.search(k.split(" / ", 1)[1]))


def _esc(s: str) -> str:
    return (s.replace("\\", "\\\\").replace('"', '\\"')
             .replace("\n", "\\n").replace("\t", "\\t").replace("\r", ""))


def _write(path: str, mapping: dict[str, str]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    lines = ["/* Auto-generated by tools/i18n/gen_strings.py — do not edit by hand. */", ""]
    for k in sorted(mapping):
        lines.append('"%s" = "%s";' % (_esc(k), _esc(mapping[k])))
    with open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write("\n".join(lines) + "\n")


def main() -> None:
    keys = _extract_keys()
    trans = json.load(open(TRANS_PATH, encoding="utf-8")) if os.path.exists(TRANS_PATH) else {}

    en: dict[str, str] = {}
    zh: dict[str, str] = {}  # only the legacy bilingual keys need a zh-Hans strip
    untranslated: list[str] = []
    for k in keys:
        if _is_bilingual(k):
            zh_half, en_half = k.split(" / ", 1)
            en[k] = en_half
            zh[k] = zh_half
        elif k in trans and trans[k].strip():
            en[k] = trans[k]
        else:
            en[k] = k  # fall back to the Chinese key until translated
            untranslated.append(k)

    _write(os.path.join(APP, "en.lproj", "Localizable.strings"), en)
    _write(os.path.join(APP, "zh-Hans.lproj", "Localizable.strings"), zh)

    bilingual = sum(1 for k in keys if _is_bilingual(k))
    print("keys=%d  en=%d  zh-Hans(strip)=%d  bilingual-auto=%d  translated=%d"
          % (len(keys), len(en), len(zh), bilingual, len(keys) - len(untranslated)))

    real = [k for k in untranslated
            if not _NON_UI.search(k) and "\\(" not in k and k != "中文"]
    if real:
        print("\n%d untranslated UI strings — add English to tools/i18n/translations.json:" % len(real))
        for k in real:
            print("   %r" % k)
    else:
        print("all user-facing strings have English (remainder are regex / data / interpolation).")


if __name__ == "__main__":
    main()
