# -*- coding: utf-8 -*-
"""Regenerate the app's Localizable.strings from the Swift sources.

Strategy (see Localization/LanguageManager.swift):
  * Every user-facing `Text("中文")` uses the Chinese literal as its
    LocalizedStringKey. We extract those literals and emit two tables:
      - en.lproj/Localizable.strings      key(中文) -> English
      - zh-Hans.lproj/Localizable.strings key(中文) -> Chinese-only
        (only needed to strip the legacy bilingual "中文 / English" labels;
         pure-Chinese keys fall back to themselves)
  * Bilingual "中文 / English" keys are split automatically.
  * Other monolingual keys take their English from translations.json.

Run from the repo root:  python tools/i18n/gen_strings.py
"""
import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APP = os.path.join(ROOT, "client", "AAALionApp", "AAALionApp")
TRANS = os.path.join(ROOT, "tools", "i18n", "translations.json")

HAN = re.compile("[一-鿿]")
LATIN = re.compile("[A-Za-z]")
LITERAL = re.compile(r'"((?:[^"\\]|\\.)*)"')


def extract_keys():
    keys = []
    seen = set()
    for path in glob.glob(os.path.join(APP, "**", "*.swift"), recursive=True):
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        for m in LITERAL.finditer(text):
            s = m.group(1)
            if HAN.search(s) and s not in seen:
                seen.add(s)
                keys.append(s)
    return keys


def is_bilingual(k):
    return " / " in k and bool(LATIN.search(k.split(" / ", 1)[1]))


def esc(s):
    return (s.replace("\\", "\\\\").replace('"', '\\"')
             .replace("\n", "\\n").replace("\t", "\\t").replace("\r", ""))


def write_strings(rel_dir, mapping):
    out_dir = os.path.join(APP, rel_dir)
    os.makedirs(out_dir, exist_ok=True)
    lines = ["/* Auto-generated by tools/i18n/gen_strings.py — do not edit by hand. */", ""]
    for k in sorted(mapping):
        lines.append('"%s" = "%s";' % (esc(k), esc(mapping[k])))
    with open(os.path.join(out_dir, "Localizable.strings"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    keys = extract_keys()
    trans = json.load(open(TRANS, encoding="utf-8")) if os.path.exists(TRANS) else {}
    en, zh = {}, {}
    biling = mono_t = mono_u = 0
    for k in keys:
        if is_bilingual(k):
            zh_half, en_half = k.split(" / ", 1)
            en[k] = en_half
            zh[k] = zh_half
            biling += 1
        elif k in trans and trans[k].strip():
            en[k] = trans[k]
            mono_t += 1
        else:
            en[k] = k          # fall back to Chinese until translated
            mono_u += 1
    write_strings("en.lproj", en)
    write_strings("zh-Hans.lproj", zh)
    print("keys=%d  bilingual=%d  translated=%d  untranslated=%d" %
          (len(keys), biling, mono_t, mono_u))
    print("en entries=%d  zh-Hans entries=%d" % (len(en), len(zh)))


if __name__ == "__main__":
    main()
